### ISSUE TITLE
Bug in weight sensor after update 3.0.0

### ISSUE THREAD

**Issue by alexreddy78** [dckiller51/bodymiscale#101]
Dear Developer,

After update to latest version, new weight sensor is updating for all “accounts” in integration. I have 3 person in there, and if I update weight for one of them, rest 2 updates same way with same weight. Have to roll back to version before 2.1.1. 

BRGDS

Alex

**Comment by Grunn95** [comment]
Having the same issue over here. The weight and impedance sensors are provided correctly and worked perfectly in the past

**Comment by snowyu** [comment]
me too.

**Comment by themsk666** [comment]
same problem here.  if one user use the scale, all 3 body sensor update from that

**Comment by pejotigrek** [comment]
same here. two users got completely messed up

**Comment by raliseda** [comment]
same here (=

**Comment by edenhaus** [comment]
Please use next time :+1: on the issue description instead of commenting "same here" as it will only spam the issue.

I was able to reproduce it and a fix is ready for review

**Comment by dckiller51** [comment]
@edenhaus 

I get this error when creating a new user. Once restarted it goes away.
Otherwise the sensors update well separately.

```Logger: homeassistant.config_entries
Source: custom_components/bodymiscale/metrics/__init__.py:296
Integration: BodyMiScale ([documentation](https://github.com/dckiller51/bodymiscale), [issues](https://github.com/dckiller51/bodymiscale/issues))
First occurred: 08:50:45 (1 occurrences)
Last logged: 08:50:45

Error setting up entry Siham for bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bodymiscale/__init__.py", line 96, in async_setup_entry
    handler = hass.data[DOMAIN][HANDLERS][entry.entry_id] = BodyScaleMetricsHandler(
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 177, in __init__
    self._state_changed(entity_id, state)
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 226, in _state_changed
    if self._is_valid(
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 280, in _is_valid
    self._update_available_metric(Metric.STATUS, PROBLEM_NONE)
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 296, in _update_available_metric
    subscribers = self._subscribers[metric]
KeyError: <Metric.STATUS: 'status'>```
