### ISSUE TITLE
Getting error during startup

### ISSUE THREAD

**Issue by kaizersoje** [dckiller51/bodymiscale#127]
I am getting the following error after startup.

```
Logger: homeassistant.config_entries
Source: custom_components/bodymiscale/metrics/__init__.py:232
Integration: BodyMiScale ([documentation](https://github.com/dckiller51/bodymiscale), [issues](https://github.com/dckiller51/bodymiscale/issues))
First occurred: 11:11:41 PM (7 occurrences)
Last logged: 11:23:12 PM

Error setting up entry Jack for bodymiscale
Error setting up entry Kim for bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bodymiscale/__init__.py", line 97, in async_setup_entry
    handler = hass.data[DOMAIN][HANDLERS][entry.entry_id] = BodyScaleMetricsHandler(
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 181, in __init__
    self._state_changed(entity_id, state)
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 232, in _state_changed
    value = float(value)
ValueError: could not convert string to float: ''
```

I have tried reloading the configurations. However, they are still not getting setup.

Have version 3.0.3 installed.

**Comment by Foguet** [comment]
I have the same problem

```
Logger: homeassistant.config_entries
Source: custom_components/bodymiscale/metrics/__init__.py:232
Integration: BodyMiScale ([documentation](https://github.com/dckiller51/bodymiscale), [issues](https://github.com/dckiller51/bodymiscale/issues))
First occurred: 21:32:46 (1 occurrences)
Last logged: 21:32:46
Error setting up entry Cayetano for bodymiscale

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bodymiscale/__init__.py", line 97, in async_setup_entry
    handler = hass.data[DOMAIN][HANDLERS][entry.entry_id] = BodyScaleMetricsHandler(
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 181, in __init__
    self._state_changed(entity_id, state)
  File "/config/custom_components/bodymiscale/metrics/__init__.py", line 232, in _state_changed
    value = float(value)
ValueError: could not convert string to float: ''
```

**Comment by dckiller51** [comment]
Hello, do you think you are in the same situation as #37 
Do your sensors have data after a reboot.
