### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by karolzamosc** [dckiller51/bodymiscale#18]
Hi,

After configuring multiple users I got this error after using the weight:

Logger: homeassistant.helpers.event
Source: custom_components/bodymiscale/body_metrics.py:20
Integration: Bodymiscale (documentation)
First occurred: 17:47:18 (1 occurrences)
Last logged: 17:47:18

Error while processing state change for sensor.weight_karol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 272, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 432, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/bodymiscale/__init__.py", line 168, in _state_changed_event
    self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
  File "/config/custom_components/bodymiscale/__init__.py", line 191, in state_changed
    self._update_state()
  File "/config/custom_components/bodymiscale/__init__.py", line 218, in _update_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 301, in state_attributes
    lib = body_metrics.bodyMetrics(weight, height, age, gender, impedance)
  File "/config/custom_components/bodymiscale/body_metrics.py", line 20, in __init__
    elif impedance > 3000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Regards,
Charles

**Comment by dckiller51** [comment]
Hello, can you copy your bodymiscale.yaml?

**Comment by karolzamosc** [comment]
> Hello, can you copy your bodymiscale.yaml?

sure, https://pastebin.com/2GA6VJU5

**Comment by dckiller51** [comment]
It seems correct to me. Delete the test user. All your users' sensors must exist in Home assistant

**Comment by karolzamosc** [comment]
> It seems correct to me. Delete the test user. All your users' sensors must exist in Home assistant

It is strange because this error is only on my user, my wife's user works fine...

**Comment by dckiller51** [comment]
your sensors weight is between 10 and 220 and impedance between 0 and 3000?

**Comment by karolzamosc** [comment]
> your sensors weight is between 10 and 220 and impedance between 0 and 3000?

Oh shit, I found the error... I had a wrong name of inpedance sensor in esphome... I am really sorry for disturbing you :( Now all works fine
