### ISSUE TITLE
Request: adding the time of the last weight acquisition

### ISSUE THREAD

**Issue by mcanteri** [dckiller51/bodymiscale#254]
Hi!
Thank you for your work, would it be possible to add the date of the last weight acquisition to the card/integration?

Thank you, best!
M.

**Comment by dckiller51** [comment]
Hello, I added this sensor in a beta version. Can you test ?

**Comment by mcanteri** [comment]
Hello, I can see the sensor sensor.person_last_measurement_time and it has the value of the last measurement but then I can see that it changes after the HA restart (update to a new version) and in some other events that I don't understand.
In the image, the red circle identifies an HA restart, but I don't know what the other events during the night were.

![Image](https://github.com/user-attachments/assets/f2ec6abd-a916-4920-ae3a-9f5322a47402)

**Comment by dckiller51** [comment]
You may be using an Esphome which reboots, I have the case with that of my scale? Unfortunately I did not find a solution for restarting, Bodyscale starts the calculation when initialized. For the map I will add it.

**Comment by mcanteri** [comment]
I keep track of the ESPHome reboots because in the past it was an issue, then I resolved it and now it is very stable, so it isn't the ESP reboot. I will try to understand in the next few days what is it.

I see in the log file this error:
2025-02-20 14:05:21.781 INFO (MainThread) [custom_components.bodymiscale]
-------------------------------------------------------------------
BodyMiScale
Version: 2024.6.0
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/dckiller51/bodymiscale/issues
-------------------------------------------------------------------

2025-02-20 14:05:21.808 ERROR (MainThread) [custom_components.bodymiscale] Error adding entity bodymiscale.michele for domain bodymiscale with platform bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 609, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 928, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bodymiscale/__init__.py", line 221, in state_attributes
    ATTR_LAST_MEASUREMENT_TIME: self._last_time,
                                ^^^^^^^^^^^^^^^
AttributeError: 'Bodymiscale' object has no attribute '_last_time'
May it be this the problem?

**Comment by dckiller51** [comment]
To correct the problem, look for the latest pre-release version in hacs. You will have version 2025.2.19-beta. It does not appear as an update. 

[Changelog](https://github.com/dckiller51/bodymiscale/blob/beta/CHANGELOG.md)

**Comment by mcanteri** [comment]
Okay, thank you, I've updated it to the latest pre-release. Will monitor it in the next few days. Best! M.

**Comment by mcanteri** [comment]
I think this issue is resolved, thank you for the support!
