### ISSUE TITLE
dckiller51/bodymiscale Install error

### ISSUE THREAD

**Issue by pedroct** [dckiller51/bodymiscale#5]
After doing the installation using the repository documentation, I restarted and this error message appeared in the HA logs:

Logger: homeassistant.setup
Source: custom_components/bodymiscale/__init__.py:280
First occurred: 12:16:14 (1 occurrences)
Last logged: 12:16:14

Error during setup of component bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f}".format(weight),
TypeError: unsupported format string passed to NoneType.__format__

`bodymiscale: !include components/bodymiscale.yaml`

My file: /config/components/bodymiscale.yaml
```
aurelien:
  sensors:
    weight: sensor.weight_aurelien
    impedance: sensor.impedance_aurelien
  height: 183
  born: "1978-02-08"
  gender: "male"
#  model_miscale: "181B"
```
```
Logger: custom_components.bodymiscale
Source: custom_components/bodymiscale/__init__.py:280
Integration: bodymiscale (documentation)
First occurred: 12:16:14 (1 occurrences)
Last logged: 12:16:14

Error adding entities for domain bodymiscale with platform bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f}".format(weight),
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by horve000** [comment]
Same error here.

Logger: homeassistant.setup
Source: custom_components/bodymiscale/__init__.py:280
First occurred: 16:45:22 (1 occurrences)
Last logged: 16:45:22

Error during setup of component bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f}".format(weight),
TypeError: unsupported format string passed to NoneType.__format__

**Comment by phil-schneider** [comment]
I have exactly the same problem.
Installed via HACS, setup all files.
Data is send from scale to esphome to home assistant. I can see my weight and impedance.
But this integration is showing the error right after booting.

**Comment by phil-schneider** [comment]
I can also see a log message with this:
  File "/config/custom_components/bodymiscale/__init__.py", line 228, in _check_max
    if value > max_value:
TypeError: '>' not supported between instances of 'str' and 'float'`
`

**Comment by dckiller51** [comment]
Update v0.0.4 fix errors

https://github.com/dckiller51/bodymiscale/releases/tag/v0.0.4 or Update via HACS
